import { ApprovalActorType, ApprovalStatus, Role } from "@prisma/client";
import { BadgeCheck, GitBranch } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { requirePage } from "@/lib/authz";
import { db } from "@/lib/db";
import { addApprovalStep, createApprovalWorkflow, decideApproval } from "./actions";

export const dynamic = "force-dynamic";
const actorNames: Record<ApprovalActorType,string>={USER:"مستخدم محدد",ROLE:"دور وظيفي",DIRECT_MANAGER:"المدير المباشر",DEPARTMENT_MANAGER:"مدير الإدارة"};
const approvalNames: Record<ApprovalStatus,string>={PENDING:"بانتظار القرار",APPROVED:"معتمد",REJECTED:"مرفوض",RETURNED:"معاد للتعديل"};

export default async function ApprovalsPage(){
  const user=await requirePage("approvals");
  const isAdmin=user.role===Role.SUPER_ADMIN;
  const [departments,users,workflows,approvals]=await Promise.all([
    db.department.findMany({where:{organizationId:user.organizationId!},select:{id:true,name:true},orderBy:{name:"asc"}}),
    db.user.findMany({where:{organizationId:user.organizationId,active:true},select:{id:true,name:true},orderBy:{name:"asc"}}),
    db.approvalWorkflow.findMany({where:{organizationId:user.organizationId!},orderBy:{createdAt:"desc"}}),
    db.approval.findMany({where:isAdmin?{}:{approverId:user.id},orderBy:[{status:"asc"},{createdAt:"desc"}],take:100}),
  ]);
  const steps=workflows.length?await db.approvalWorkflowStep.findMany({where:{workflowId:{in:workflows.map((workflow)=>workflow.id)}},orderBy:[{workflowId:"asc"},{stepOrder:"asc"}]}):[];
  const departmentNames=new Map(departments.map((item)=>[item.id,item.name]));const userNames=new Map(users.map((item)=>[item.id,item.name]));const stepsByWorkflow=new Map<string,typeof steps>();for(const step of steps)stepsByWorkflow.set(step.workflowId,[...(stepsByWorkflow.get(step.workflowId)??[]),step]);
  return <DashboardShell><div className="p-5 lg:p-8"><div className="flex items-center gap-3"><span className="rounded-xl bg-teal-50 p-3 text-teal-700"><BadgeCheck/></span><div><h1 className="text-2xl font-bold">مركز الاعتمادات</h1><p className="text-sm text-slate-500">سلسلة موافقات حسب الإدارة: الموظف ← المدير المباشر ← مدير الإدارة ← الإدارة التنفيذية</p></div></div>
    {isAdmin&&<><form action={createApprovalWorkflow} className="card mt-6 grid gap-3 p-5 md:grid-cols-[1fr_1fr_1fr_auto]"><input name="name" required placeholder="اسم سلسلة الموافقات" className="rounded-lg border p-3"/><select name="departmentId" required className="rounded-lg border p-3"><option value="">اختر الإدارة</option>{departments.map((department)=><option key={department.id} value={department.id}>{department.name}</option>)}</select><select name="entityType" className="rounded-lg border p-3"><option value="REPORT">تقارير الإدارة</option><option value="INITIATIVE_UPDATE">تحديث مبادرة</option><option value="KPI_TARGET">تعديل مستهدف KPI</option></select><button className="rounded-lg bg-teal-700 px-5 font-bold text-white">إنشاء السلسلة</button></form>
    <div className="mt-5 space-y-4">{workflows.map((workflow)=><article key={workflow.id} className="card p-5"><div className="flex items-center gap-3"><GitBranch className="text-teal-700"/><div><h2 className="font-bold">{workflow.name}</h2><p className="text-xs text-slate-500">{departmentNames.get(workflow.departmentId??"")} · {workflow.entityType}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{(stepsByWorkflow.get(workflow.id)??[]).map((step)=><span key={step.id} className="rounded-full bg-slate-100 px-3 py-2 text-xs"><b>{step.stepOrder}. {step.name}</b> · {actorNames[step.actorType]} {step.approverUserId?`(${userNames.get(step.approverUserId)})`:step.approverRole?`(${step.approverRole})`:""}</span>)}</div><details className="mt-4 rounded-xl border p-3"><summary className="cursor-pointer text-sm font-bold">إضافة أو تعديل خطوة</summary><form action={addApprovalStep} className="mt-3 grid gap-2 md:grid-cols-3"><input type="hidden" name="workflowId" value={workflow.id}/><input name="stepOrder" type="number" min="1" required placeholder="ترتيب الخطوة" className="rounded-lg border p-2"/><input name="name" required placeholder="اسم الخطوة" className="rounded-lg border p-2"/><select name="actorType" className="rounded-lg border p-2">{Object.values(ApprovalActorType).map((type)=><option key={type} value={type}>{actorNames[type]}</option>)}</select><select name="approverRole" className="rounded-lg border p-2"><option value="">بدون دور محدد</option>{Object.values(Role).map((role)=><option key={role} value={role}>{role}</option>)}</select><select name="approverUserId" className="rounded-lg border p-2"><option value="">بدون مستخدم محدد</option>{users.map((member)=><option key={member.id} value={member.id}>{member.name}</option>)}</select><button className="rounded-lg border border-teal-700 p-2 font-bold text-teal-800">حفظ الخطوة</button></form></details></article>)}</div></>}
    <section className="mt-7"><h2 className="text-lg font-bold">طلبات الاعتماد</h2><div className="mt-3 space-y-3">{approvals.map((approval)=><article key={approval.id} className="card p-5"><div className="flex flex-wrap justify-between gap-3"><div><b>{approval.entityType} · الخطوة {approval.stepOrder}</b><p className="text-xs text-slate-500">المعتمد: {userNames.get(approval.approverId??"")??"لم يحدد"}</p></div><span className="badge bg-amber-50 text-amber-800">{approvalNames[approval.status]}</span></div>{approval.status===ApprovalStatus.PENDING&&(isAdmin||approval.approverId===user.id)&&<form action={decideApproval} className="mt-4 grid gap-2 md:grid-cols-[1fr_auto_auto_auto]"><input type="hidden" name="approvalId" value={approval.id}/><input name="comment" placeholder="تعليق القرار" className="rounded-lg border p-2"/><button name="decision" value="approve" className="rounded-lg bg-emerald-700 px-4 py-2 text-white">اعتماد</button><button name="decision" value="return" className="rounded-lg bg-amber-100 px-4 py-2 text-amber-900">إعادة</button><button name="decision" value="reject" className="rounded-lg bg-red-100 px-4 py-2 text-red-800">رفض</button></form>}</article>)}{approvals.length===0&&<div className="card p-10 text-center text-slate-500">لا توجد طلبات اعتماد في نطاقك.</div>}</div></section>
  </div></DashboardShell>;
}
